version: 2

project_name: codexcw

before:
  hooks:
    - go mod tidy

builds:
  - id: codexcw
    skip: true

archives: []

checksum:
  disable: true

sboms: []

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]-]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]-]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  draft: false
  prerelease: auto
  name_template: '{{ .ProjectName }} {{ .Version }}'
