/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A batch of running `codex exec` processes. */
export declare class Group {
  /** Awaits the next multiplexed event, or `null` once every run finishes. */
  nextEvent(): Promise<JsRunEvent | null>
  /** Returns every run result. */
  wait(): Promise<Array<JsGroupResult>>
  /** Stops all active and pending runs. */
  cancel(): void
}

/** Starts `codex exec` processes with safe automation defaults. */
export declare class Runner {
  /**
   * Creates a runner, optionally overriding defaults. Unknown
   * `defaultSandbox`/`defaultApproval` strings fall back to the safe
   * defaults (read-only, never); the TypeScript types constrain them.
   */
  constructor(options?: JsRunnerOptions | undefined | null)
  /**
   * Launches one process and returns a [`Session`]. Never rejects: request
   * or spawn failures surface through the session's `wait()` outcome.
   */
  start(req: JsRequest): Promise<Session>
  /** Runs one process to completion and returns its outcome. */
  runRaw(req: JsRequest): Promise<JsOutcome>
  /** Launches many processes with bounded concurrency. */
  runMany(reqs: Array<JsRequest>, options?: JsManyOptions | undefined | null): Promise<Group>
}

/**
 * A running `codex exec` process. Prefer the `events()` async iterator and
 * `wait()` exposed by the `index.js` wrapper over these raw methods.
 */
export declare class Session {
  /** Awaits the next decoded event, or `null` once the stream closes. */
  nextEvent(): Promise<JsEvent | null>
  /** Waits for the process to exit and returns its outcome. */
  wait(): Promise<JsOutcome>
  /** The wrapper-assigned run id. */
  get id(): string
  /** The Codex thread id once known. */
  threadId(): string
  /** Stops the child process. */
  cancel(): void
}

/** One `-c key=value` config override. */
export interface JsConfigOverride {
  key: string
  value: string
}

/** A typed run error. */
export interface JsError {
  /**
   * One of: `promptRequired`, `invalidRequest`, `exit`, `decode`, `codex`,
   * `handler`, `cancelled`, `process`.
   */
  kind: string
  message: string
  code?: number
  stderr?: string
  line?: number
}

/** One decoded Codex event. */
export interface JsEvent {
  type: string
  runId: string
  threadId: string
  raw: string
  item?: JsItem
  usage?: JsUsage
  error?: string
}

/** One file edit inside a `file_change` item. */
export interface JsFileChange {
  path: string
  kind: string
}

/** One result from `runMany`. */
export interface JsGroupResult {
  index: number
  runId: string
  result?: JsRunResult
  error?: Error
}

/** A typed projection of a Codex item. */
export interface JsItem {
  id: string
  type: string
  status: string
  text: string
  message: string
  command: string
  aggregatedOutput: string
  exitCode?: number
  raw: string
  changes: Array<JsFileChange>
}

/** Options for `runMany`. */
export interface JsManyOptions {
  maxConcurrent?: number
  eventBuffer?: number
}

/** A run result paired with any terminal error. */
export interface JsOutcome {
  result: JsRunResult
  error?: Error
}

/** A Codex run request. All fields are optional except prompt or stdin. */
export interface JsRequest {
  prompt?: string
  stdin?: string
  dir?: string
  addDirs?: Array<string>
  images?: Array<string>
  model?: string
  profile?: string
  sandbox?: string
  approval?: string
  config?: Array<JsConfigOverride>
  enable?: Array<string>
  disable?: Array<string>
  strictConfig?: boolean
  persistent?: boolean
  ignoreUserConfig?: boolean
  ignoreRules?: boolean
  requireGitRepo?: boolean
  outputSchemaPath?: string
  outputSchema?: string
  outputLastMessagePath?: string
  dangerouslyBypassSandbox?: boolean
  dangerouslyBypassHooks?: boolean
  env?: Record<string, string>
  resumeId?: string
  resumeLast?: boolean
  resumeAll?: boolean
}

/** One multiplexed event from `runMany`. */
export interface JsRunEvent {
  runId: string
  index: number
  event: JsEvent
}

/** Options for constructing a [`Runner`]. */
export interface JsRunnerOptions {
  executable?: string
  env?: Record<string, string>
  eventBuffer?: number
  stderrLimit?: number
  scanMaxBytes?: number
  defaultSandbox?: string
  defaultApproval?: string
}

/** Summary of a completed run. */
export interface JsRunResult {
  runId: string
  threadId: string
  finalMessage: string
  usage: JsUsage
  events: Array<JsEvent>
  stderr: string
  startedAtMs: number
  finishedAtMs: number
}

/** Token usage reported by Codex. */
export interface JsUsage {
  inputTokens: number
  cachedInputTokens: number
  outputTokens: number
  reasoningOutputTokens: number
  totalTokens: number
}
