/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A batch of running selected-agent processes. */
export declare class Group {
  /** Awaits the next multiplexed event, or `null` once every run finishes. */
  nextEvent(): Promise<JsRunEvent | null>
  /** Returns every run result. */
  wait(): Promise<Array<JsGroupResult>>
  /** Stops all active and pending runs. */
  cancel(): void
}

/** Starts selected-agent processes with safe automation defaults. */
export declare class Runner {
  /**
   * Creates a runner, optionally overriding defaults. Unknown
   * `defaultSandbox`/`defaultApproval` strings fall back to the safe
   * defaults (read-only, never); the TypeScript types constrain them.
   */
  constructor(options?: JsRunnerOptions | undefined | null)
  /**
   * Launches one process and returns a [`Session`]. Never rejects: request
   * or spawn failures surface through the session's `wait()` outcome.
   */
  start(req: JsRequest): Promise<Session>
  /** Runs one process to completion and returns its outcome. */
  runRaw(req: JsRequest): Promise<JsOutcome>
  /** Launches many processes with bounded concurrency. */
  runMany(reqs: Array<JsRequest>, options?: JsManyOptions | undefined | null): Promise<Group>
}

/**
 * A running selected-agent process. Prefer the `events()` async iterator and
 * `wait()` exposed by the `index.js` wrapper over these raw methods.
 */
export declare class Session {
  /** Awaits the next decoded event, or `null` once the stream closes. */
  nextEvent(): Promise<JsEvent | null>
  /** Waits for the process to exit and returns its outcome. */
  wait(): Promise<JsOutcome>
  /** The wrapper-assigned run id. */
  get id(): string
  /** The agent thread or session id once known. */
  threadId(): string
  /** Stops the child process. */
  cancel(): void
}

/** Reads Codex account usage and limits through `codex app-server`. */
export declare function getAccountUsageRaw(req?: JsAccountUsageRequest | undefined | null): Promise<JsAccountUsageOutcome>

/** Reads Claude account usage through the Claude Code `/usage` command. */
export declare function getClaudeAccountUsageRaw(req?: JsClaudeAccountUsageRequest | undefined | null): Promise<JsClaudeAccountUsageOutcome>

/** Codex credit balance snapshot. */
export interface JsAccountCredits {
  hasCredits: boolean
  unlimited: boolean
  balance?: string
}

/** One Codex rate-limit set. */
export interface JsAccountRateLimits {
  limitId: string
  limitName: string
  primary?: JsAccountRateLimitWindow
  secondary?: JsAccountRateLimitWindow
  credits?: JsAccountCredits
  individualLimit?: JsAccountSpendLimit
  planType: string
  rateLimitReachedType: string
}

/** One account usage window. */
export interface JsAccountRateLimitWindow {
  usedPercent: number
  windowDurationMins: number
  resetsAt: number
}

/** Individual spend or credit-control limit. */
export interface JsAccountSpendLimit {
  limit: number
  used: number
  remainingPercent: number
  resetsAt: number
}

/** Account token-usage summary reported by Codex. */
export interface JsAccountTokenUsage {
  summary: JsAccountTokenUsageSummary
  dailyUsageBuckets: Array<JsAccountTokenUsageDailyBucket>
}

/** One daily account token-usage bucket. */
export interface JsAccountTokenUsageDailyBucket {
  startDate: string
  tokens: string
}

/** Aggregate account token-usage metrics. */
export interface JsAccountTokenUsageSummary {
  lifetimeTokens?: string
  peakDailyTokens?: string
  longestRunningTurnSec?: string
  currentStreakDays?: string
  longestStreakDays?: string
}

/** Codex account limits and credits. */
export interface JsAccountUsage {
  account?: JsAccountUsageAccount
  tokenUsage?: JsAccountTokenUsage
  rateLimits: JsAccountRateLimits
  rateLimitsByLimitId: Record<string, JsAccountRateLimits>
  rawRateLimits: string
  rawTokenUsage?: string
  rawAccount?: string
}

/** Authenticated account reported by Codex. */
export interface JsAccountUsageAccount {
  type: string
  email: string
  planType: string
  requiresOpenaiAuth: boolean
}

/** Account usage result paired with any terminal error. */
export interface JsAccountUsageOutcome {
  result?: JsAccountUsage
  error?: Error
}

/** Options for reading Codex account usage. */
export interface JsAccountUsageRequest {
  executable?: string
  env?: Record<string, string>
  /** Per-request JSON-RPC timeout in milliseconds. Defaults to 10 seconds. */
  timeoutMs?: number
}

/** Claude account usage report. */
export interface JsClaudeAccountUsage {
  report: string
  windows: Array<JsClaudeAccountUsageWindow>
  raw: string
}

/** Claude account usage paired with any terminal error. */
export interface JsClaudeAccountUsageOutcome {
  result?: JsClaudeAccountUsage
  error?: Error
}

/** Options for reading Claude account usage. */
export interface JsClaudeAccountUsageRequest {
  executable?: string
  env?: Record<string, string>
  /** Timeout in milliseconds. Defaults to 10 seconds. */
  timeoutMs?: number
}

/** One Claude usage window. */
export interface JsClaudeAccountUsageWindow {
  label: string
  usedPercent: number
  resetsAt: string
}

/** One `-c key=value` config override. */
export interface JsConfigOverride {
  key: string
  value: string
}

/** A typed run error. */
export interface JsError {
  /**
   * One of: `promptRequired`, `invalidRequest`, `exit`, `decode`, `codex`,
   * `claude`, `handler`, `cancelled`, `process`.
   */
  kind: string
  message: string
  code?: number
  stderr?: string
  line?: number
}

/** One decoded agent event. */
export interface JsEvent {
  type: string
  runId: string
  threadId: string
  raw: string
  item?: JsItem
  usage?: JsUsage
  error?: string
}

/** One file edit inside a `file_change` item. */
export interface JsFileChange {
  path: string
  kind: string
}

/** One result from `runMany`. */
export interface JsGroupResult {
  index: number
  runId: string
  result?: JsRunResult
  error?: Error
}

/** A typed projection of an agent item. */
export interface JsItem {
  id: string
  type: string
  status: string
  text: string
  message: string
  command: string
  aggregatedOutput: string
  exitCode?: number
  raw: string
  changes: Array<JsFileChange>
}

/** Options for `runMany`. */
export interface JsManyOptions {
  maxConcurrent?: number
  eventBuffer?: number
}

/** Per-model usage reported by an agent. */
export interface JsModelUsage {
  inputTokens: number
  outputTokens: number
  cacheReadInputTokens: number
  cacheCreationInputTokens: number
  webSearchRequests: number
  costUsd: number
  contextWindow: number
  maxOutputTokens: number
}

/** A run result paired with any terminal error. */
export interface JsOutcome {
  result: JsRunResult
  error?: Error
}

/** An agent run request. All fields are optional except prompt or stdin. */
export interface JsRequest {
  prompt?: string
  stdin?: string
  dir?: string
  addDirs?: Array<string>
  images?: Array<string>
  model?: string
  profile?: string
  sandbox?: string
  approval?: string
  permissionMode?: string
  allowedTools?: Array<string>
  disallowedTools?: Array<string>
  config?: Array<JsConfigOverride>
  enable?: Array<string>
  disable?: Array<string>
  strictConfig?: boolean
  persistent?: boolean
  ignoreUserConfig?: boolean
  ignoreRules?: boolean
  requireGitRepo?: boolean
  outputSchemaPath?: string
  outputSchema?: string
  outputLastMessagePath?: string
  dangerouslyBypassSandbox?: boolean
  dangerouslyBypassHooks?: boolean
  env?: Record<string, string>
  resumeId?: string
  resumeLast?: boolean
  resumeAll?: boolean
}

/** One multiplexed event from `runMany`. */
export interface JsRunEvent {
  runId: string
  index: number
  event: JsEvent
}

/** Options for constructing a [`Runner`]. */
export interface JsRunnerOptions {
  /** Which agent CLI to wrap: `codex` (default) or `claude`. */
  agent?: string
  executable?: string
  env?: Record<string, string>
  eventBuffer?: number
  stderrLimit?: number
  scanMaxBytes?: number
  defaultSandbox?: string
  defaultApproval?: string
}

/** Summary of a completed run. */
export interface JsRunResult {
  runId: string
  threadId: string
  finalMessage: string
  usage: JsUsage
  events: Array<JsEvent>
  stderr: string
  startedAtMs: number
  finishedAtMs: number
}

/** Token usage reported by an agent. */
export interface JsUsage {
  inputTokens: number
  cachedInputTokens: number
  cacheCreationInputTokens: number
  outputTokens: number
  reasoningOutputTokens: number
  totalTokens: number
  totalCostUsd: number
  modelUsage: Record<string, JsModelUsage>
}
